### ISSUE TITLE
Don't execute interval'd function immediately

### ISSUE THREAD

**Issue by joeyfigaro** [elselabs/redux-timer#2]
I'd like to use this to set up background syncing every five minutes, but sync is being executed as soon as `START_TIMER` fires. I imagined the initial action would set up the interval, but that's it.

**Comment by btav** [comment]
@joeyfigaro We can add a `runImmediately` flag that will control whether or not it would execute when `START_TIMER` fires.

**Comment by btav** [comment]
@joeyfigaro this has been merged and available in version `1.1.3`.
