### ISSUE TITLE
Action as a Function - Pass getState

### ISSUE THREAD

**Issue by george2seven** [elselabs/redux-timer#4]
Hello, 

I am trying to use the "Action as a Function" option

import { START_TIMER } from 'redux-timer';

export const exampleAction = () => async dispatch => {
  dispatch({
    type: START_TIMER,
    payload: {
      name: 'exampleTimer',
      action: async (getState) => {
         **const {[something from store} = getState();
         //the above line produces an error "getState is not a function"**
         //do something here
      },
      interval: 5000,
      runImmediately: false
    }
  });
};

Can you please guide me as to how I can expose the getState function within the function?

Thank you very much

**Comment by btav** [comment]
Hi @george2seven,

Can you try adding `getState` beside `dispatch` as a parameter in `exampleAction()`.

Like the following?

`export const exampleAction = () => (dispatch, getState) => {`

**Comment by george2seven** [comment]
Thank you very much @btav ! It works!
